name: dino-ldm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=mkl
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cudatoolkit=11.3.1=hb98b00a_13
  - einops=0.6.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - fire=0.4.0=pyh44b312d_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.3.0=h59595ed_1
  - gnutls=3.6.13=h85f3911_1
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.12.6=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=18.1.2=h4dfa4b3_0
  - mako=1.2.3=py310h06a4308_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.2.0=h84fe81f_50496
  - mkl-service=2.4.1=py310hc72dfd8_0
  - mkl_fft=1.3.8=py310ha3dbc2a_1
  - mkl_random=1.2.5=py310hbd113e2_1
  - ncurses=6.4.20240210=h59595ed_0
  - nettle=3.6=he412f7d_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.0.13=h7f8727e_0
  - pillow=9.4.0=py310h023d228_1
  - pip=24.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.6=ha86cf86_0_cpython
  - python_abi=3.10=4_cp310
  - pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tbb=2021.11.0=h00ab1b0_1
  - termcolor=2.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchvision=0.13.1=py310_cu113
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.24.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - argcomplete==3.2.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - boto==2.49.0
      - chex==0.1.86
      - clu==0.0.11
      - contextlib2==21.6.0
      - crcmod==1.7
      - cryptography==42.0.5
      - cycler==0.12.1
      - datasets==2.7.1
      - diffusers==0.18.2
      - dill==0.3.6
      - etils==1.7.0
      - fasteners==0.19
      - flax==0.8.2
      - frozenlist==1.4.1
      - gcs-oauth2-boto-plugin==3.0
      - google-apitools==0.5.32
      - google-reauth==0.1.1
      - googleapis-common-protos==1.63.0
      - gsutil==5.27
      - h5py==3.10.0
      - httplib2==0.20.4
      - imageio==2.34.0
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - jax==0.4.25
      - jaxlib==0.4.25
      - keras==3.1.1
      - kornia==0.6.12
      - lazy-loader==0.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - medmnist==3.0.1
      - ml-collections==0.1.1
      - ml-dtypes==0.3.2
      - monotonic==1.6
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.14
      - namex==0.0.7
      - nest-asyncio==1.6.0
      - oauth2client==4.1.3
      - optax==0.2.2
      - optree==0.11.0
      - orbax-checkpoint==0.5.7
      - packaging==24.0
      - promise==2.3
      - protobuf==3.20.3
      - pyarrow==15.0.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygments==2.17.2
      - pyopenssl==24.1.0
      - pyu2f==0.1.5
      - pyyaml==6.0.1
      - responses==0.18.0
      - retry-decorator==1.1.1
      - rich==13.7.1
      - rsa==4.7.2
      - safetensors==0.2.8
      - scikit-image==0.22.0
      - seaborn==0.12.2
      - tensorflow==2.16.1
      - tensorflow-datasets==4.7.0
      - tensorflow-metadata==1.14.0
      - tensorstore==0.1.56
      - tifffile==2024.2.12
      - timm==0.6.13
      - tokenizers==0.13.3
      - toml==0.10.2
      - toolz==0.12.1
      - transformers==4.25.1
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.18.1