name: rep-ldm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - numpy
  - pillow
  - ffmpeg
  - einops
  - fire
  - requests
  - setuptools
  - pip
  - pip:
      - absl-py==1.4.0
      - accelerate==0.24.1
      - aiohttp==3.9.3
      - chex==0.1.86
      - datasets==2.7.1
      - diffusers==0.18.2
      - flax==0.8.2
      - h5py==3.10.0
      - imageio==2.34.0
      - jax==0.4.25
      - jaxlib==0.4.25
      - keras==3.1.1
      - kornia==0.6.12
      - matplotlib
      - ml-collections==0.1.1
      - optax==0.2.2
      - protobuf==3.20.3
      - scikit-image==0.22.0
      - seaborn==0.12.2
      - timm==0.6.13
      - transformers==4.25.1
      - pyyaml
      - rich
      - wandb