#=== Directories ===#
output_dir: /proj/dcdl/users/gabei62/rep-ldm/output/       
data_dir: /scratch/local/rep-ldm/ffhq/images/ffhq512                              
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4  

#=== Data Setup ===# 
seed: 42                                                                            
resolution: 512                                                            
batch_size: 6                                            
dataset: ffhq                                            
trials: diffae-ffhq                              

#=== Pre-trained Encoder Config ===#
encoder_name: KL                                             
channels: 4                                               
rep_encoder: test

#=== Semantic Encoder ===#
embed_dim: 512
enc_channels: 128
channel_multipliers: [1,1,2,2,4,4,4]
num_resnet_blocks: 2
resnet_dropout: 0.1
attn_resolution: [16]
use_conv_resample: True
num_groups: 32

#=== Training U-Net ===#
lr: 0.00005                                                                        
beta_1: 0.9                                                           
beta_2:  0.999                                                
weight_decay: 0.001                                           
lr_scheduler: lambdalinear                                       
num_train_epochs: 100                                      
gradient_accumulation_steps: 1                             
name: diffae-unet-ffhq                                 
checkpoint_epoch: 10                                                                            
prev_step: 0
validation: True
train_from_scratch: False
resume_path: /proj/dcdl/users/gabei62/rep-ldm/output/diffae-ffhq/model/diffae-unet-ffhq_epoch91_step227500.pt

#=== Sampling U-Net ===#
method: diffae
scheduler: ddpm
noise_strength: 0.0
guidance_scale: 6
num_samples: 8
infsteps: 100 
sampling: seed  