#=== Directories ===#
output_dir: /proj/dcdl/users/gabei62/rep-ldm/output/       
data_dir: /proj/dcdl/users/gabei62/rep-ldm/data/test_data                   
rep_dir: /proj/dcdl/users/gabei62/rep-ldm/rep/test_rep                
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4  

#=== Data Setup ===# 
seed: 42                                                                            
resolution: 512                                                            
batch_size: 8                                            
dataset: ffhq                                            
trials: test                            

#=== Pre-trained Encoder Config ===#
encoder_name: KL                                             
channels: 4                                               
rep_encoder: test                                     
embed_dim: 768

#=== Training U-Net ===#
lr: 0.00005                                                                        
beta_1: 0.9                                                           
beta_2:  0.999                                                
weight_decay: 0.001                                           
lr_scheduler: lambdalinear                                       
num_train_epochs: 1000                                      
gradient_accumulation_steps: 1                             
name: test                                
checkpoint_epoch: 25                                                                            
prev_step: 0
validation: True
train_from_scratch: False
resume_path: /proj/dcdl/users/gabei62/rep-ldm/output/clip-ldm-imagenet-100/model/clip-ldm-unet-imagenet-100_epoch101_step205232.pt

#=== Sampling U-Net ===#
method: dino-ldm
scheduler: ddpm
noise_strength: 0.0
guidance_scale: 6
num_samples: 8
infsteps: 100 
sampling: seed  